project:
  type: website
  output-dir: _site
  resources:
    - "/docs/download/_download.json"
    - "/docs/download/_prerelease.json"
    - "/_redirects"

website:
  title: "OS in Pharma"
  image: "images/opensourceInPharma_transparent.png"
  favicon: "favicon.png"
  google-analytics: "G-SRBLBCD4NS"
  open-graph: true
  twitter-card: true
  site-url: https://opensourceinpharma.com
  repo-url: https://github.com/OpenSourceinPharma/OpenSourceinPharma
  repo-actions: [edit, issue]
  page-navigation: true
  page-footer:
    left: |
      Proud organizer of 
      [![](/images/logo-rinpharma.png){fig-alt="OS in Pharma logo" width=65px}](https://www.rinpharma.com)
    center:
      - text: "About"
        href: about.qmd
      - text: "FAQ"
        href: docs/faq/index.qmd
      - text: "License"
        href: license.qmd
    right:
      - icon: twitter
        href: https://twitter.com/OpenSourceinPharma
        aria-label: R/Pharma Twitter
      - icon: github
        href: https://github.com/openpharma
        aria-label: OpenPharma github
#      - icon: rss
#        href: 
#        aria-label:      
  navbar:
    background: light
    logo: images/opensourceInPharma_white.png
    logo-alt: "Quarto logo."
    title: false
    collapse-below: lg
    left:
      - text: "Overview"
        href: index.qmd
      - text: Governance
        href: docs/governance/index.qmd
      - text: "Blog"
        href: docs/blog/index.qmd
    right:
      - icon: twitter
        href: https://twitter.com/rinpharma
        aria-label: R/Pharma Twitter
      - icon: github
        href: https://github.com/openpharma
        aria-label: OpenPharma github
#      - icon: rss
#        href: 
#        aria-label:         

format:
  html:
    toc: true
    theme:
      light: [cosmo, theme.scss]
    code-copy: true
    code-overflow: wrap
    css: styles.css
    include-after-body: js.html

filters:
  - filters/tools-tabset.lua


execute:
  freeze: auto

editor: visual
