project:
  type: website
  output-dir: _site
  resources:
    - "/docs/download/_download.json"
    - "/docs/download/_prerelease.json"
    - "/_redirects"

website:
  title: "OS in Pharma"
  image: "images/opensourceInPharma_transparent.png"
  favicon: "favicon.png"
  google-analytics: "G-FV9Z7SDZ0M"
  open-graph: true
  twitter-card: true
  site-url: https://opensourceinpharma.com
  repo-url: https://github.com/OpenSourceinPharma/osinpharma-site
  repo-actions: [edit, issue]
  page-navigation: true
  search:
    algolia:
      index-name: prod_QUARTO
      application-id: ZPJB5I1QN7
      search-only-api-key: 41be6c1e0a7fea4a51b107810facf577
      analytics-events: true
      show-logo: true
  page-footer:
    left: |
      Proud organizer of 
      [![](/images/logo-rinpharma.png){fig-alt="OS in Pharma logo" width=65px}](https://www.rinpharma.com)
    center:
      - text: "About"
        href: about.qmd
      - text: "FAQ"
        href: docs/faq/index.qmd
      - text: "License"
        href: license.qmd
    right:
      - icon: twitter
        href: https://twitter.com/rinpharma
        aria-label: R/Pharma Twitter
      - icon: github
        href: https://github.com/openpharma
        aria-label: OpenPharma github
#      - icon: rss
#        href: https://quarto.org/docs/blog/index.xml
#        aria-label: Quarto Blog RSS        
  navbar:
    background: light
    logo: images/opensourceInPharma_white.png
    logo-alt: "Quarto logo."
    title: false
    collapse-below: lg
    left:
      - text: "Overview"
        href: index.qmd
#      - text: "Guide"
#        href: docs/guide/index.qmd
      - text: Governance
        href: docs/governance/index.qmd
#      - text: "Reference"
#        href: docs/reference/index.qmd
#      - text: "Gallery"
#        href: docs/gallery/index.qmd
      - text: "Blog"
        href: docs/blog/index.qmd
#      - text: "Help"
#        menu:
#          - text: "Report a Bug"
#            icon: "bug"
#            href: "https://github.com/quarto-dev/quarto-cli/issues"
#          - text: "Ask a Question"
#            icon: "chat-right-text"
#            href: "https://github.com/quarto-dev/quarto-cli/discussions"
#          - text: "FAQ"
#            icon: "question-circle"
#            href: docs/faq/index.qmd
    right:
      - icon: twitter
        href: https://twitter.com/rinpharma
        aria-label: R/Pharma Twitter
      - icon: github
        href: https://github.com/openpharma
        aria-label: OpenPharma github
#      - icon: rss
#        href: https://quarto.org/docs/blog/index.xml
#        aria-label: Quarto Blog RSS        

format:
  html:
    toc: true
    theme:
      light: [cosmo, theme.scss]
    code-copy: true
    code-overflow: wrap
    css: styles.css
    include-after-body: js.html

filters:
  - filters/tools-tabset.lua


freeze: true

editor: visual
